export * from "./Headline";
export * from "./Card";
export * from "./Bill";
export * from "./CardTitle";
export * from "./InputWrapper";
export * from './PeopleNumber';
export * from './ButtonPrimary';
export * from './Tips';
export * from './TotalCard'